# Generated by Django 3.0.6 on 2020-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='zdjęcie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(verbose_name='Opis'),
        ),
    ]
